valid_words = {
    "apple", "elephant", "tree", "egg", "game", "ear", "rat", "tap", "pot",
    "top", "pen", "notebook", "keyboard", "dog", "goat", "tag", "glass",
    "snake", "envelope", "emotion", "nest", "tiger", "rock", "kick", "kite",
    "engine", "exit", "table", "exam", "moon", "note", "eagle", "easy",
    "yellow", "white", "earring", "guitar", "ring", "grape", "echo", "ocean",
    "nail", "lamp", "pin", "network", "king", "gold", "diamond", "drum",
    "magic", "camera", "arrow", "wish", "hat", "tennis", "sun", "nurse",
    "engineer", "robot", "tank", "kite", "energy", "yoga", "actor", "rain",
    "ninja", "angel", "lion", "nose", "earth", "honey", "yard", "drive",
    "electric", "cup", "pan", "nest", "tower", "road", "dance", "echo",
    "octopus", "spoon", "nobody", "young", "grin", "nap", "police", "eclipse",
    "eggplant", "teacher", "rabbit", "tea", "album", "milk", "kitten",
    "number", "ride", "ear", "run", "note", "edge", "emotion", "novel",
    "level", "laptop", "plant", "ticket", "time", "element", "tornado",
    "orange", "eye", "engine", "elk", "kangaroo", "owl", "lamp", "pencil",
    "lighthouse", "evening", "giggle", "exit", "tail", "loop", "pie", "echo",
    "orbit", "token", "night", "tent", "telephone", "elevator", "radar",
    "rush", "hill", "lemon", "newspaper", "ring", "giant", "tea", "anchor",
    "rocket", "tap", "pen", "napkin", "nut", "top", "pool", "lake", "enemy",
    "yield", "dream", "mouse", "energy", "yell", "lamp", "pick", "kite",
    "elephant", "touch", "hatch", "hope", "egg", "grab", "basket", "tail",
    "lane", "exit", "tuna", "angle", "echo", "owl", "leaf", "fish", "hat",
    "tip", "peach", "hill", "line", "egg", "guess"
}
